/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'root': RouteRecordInfo<'root', '/', Record<never, never>, Record<never, never>>,
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'academy-course-details': RouteRecordInfo<'academy-course-details', '/academy/course-details', Record<never, never>, Record<never, never>>,
    'academy-dashboard': RouteRecordInfo<'academy-dashboard', '/academy/dashboard', Record<never, never>, Record<never, never>>,
    'academy-my-course': RouteRecordInfo<'academy-my-course', '/academy/my-course', Record<never, never>, Record<never, never>>,
    'acesso-perfis': RouteRecordInfo<'acesso-perfis', '/acesso/perfis', Record<never, never>, Record<never, never>>,
    'acesso-perfis-components-add-edit-role-dialog': RouteRecordInfo<'acesso-perfis-components-add-edit-role-dialog', '/acesso/perfis/components/AddEditRoleDialog', Record<never, never>, Record<never, never>>,
    'acesso-perfis-components-role-cards': RouteRecordInfo<'acesso-perfis-components-role-cards', '/acesso/perfis/components/RoleCards', Record<never, never>, Record<never, never>>,
    'acesso-perfis-components-user-list': RouteRecordInfo<'acesso-perfis-components-user-list', '/acesso/perfis/components/UserList', Record<never, never>, Record<never, never>>,
    'acesso-permissoes': RouteRecordInfo<'acesso-permissoes', '/acesso/permissoes', Record<never, never>, Record<never, never>>,
    'acesso-permissoes-components-add-edit-permission-dialog': RouteRecordInfo<'acesso-permissoes-components-add-edit-permission-dialog', '/acesso/permissoes/components/AddEditPermissionDialog', Record<never, never>, Record<never, never>>,
    'auth-esqueceu-senha': RouteRecordInfo<'auth-esqueceu-senha', '/auth/esqueceu-senha', Record<never, never>, Record<never, never>>,
    'auth-login': RouteRecordInfo<'auth-login', '/auth/login', Record<never, never>, Record<never, never>>,
    'auth-redefinir-senha': RouteRecordInfo<'auth-redefinir-senha', '/auth/redefinir-senha', Record<never, never>, Record<never, never>>,
    'auth-verificar-email': RouteRecordInfo<'auth-verificar-email', '/auth/verificar-email', Record<never, never>, Record<never, never>>,
    'profile': RouteRecordInfo<'profile', '/profile', Record<never, never>, Record<never, never>>,
    'users': RouteRecordInfo<'users', '/users', Record<never, never>, Record<never, never>>,
    'users-cadastrar': RouteRecordInfo<'users-cadastrar', '/users/cadastrar', Record<never, never>, Record<never, never>>,
    'users-components-form-users': RouteRecordInfo<'users-components-form-users', '/users/components/form-users', Record<never, never>, Record<never, never>>,
    'users-editar-id': RouteRecordInfo<'users-editar-id', '/users/editar/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
  }
}
