/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'root': RouteRecordInfo<'root', '/', Record<never, never>, Record<never, never>>,
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'acesso-perfis': RouteRecordInfo<'acesso-perfis', '/acesso/perfis', Record<never, never>, Record<never, never>>,
    'acesso-perfis-components-add-edit-role-dialog': RouteRecordInfo<'acesso-perfis-components-add-edit-role-dialog', '/acesso/perfis/components/AddEditRoleDialog', Record<never, never>, Record<never, never>>,
    'acesso-perfis-components-role-cards': RouteRecordInfo<'acesso-perfis-components-role-cards', '/acesso/perfis/components/RoleCards', Record<never, never>, Record<never, never>>,
    'acesso-perfis-components-user-list': RouteRecordInfo<'acesso-perfis-components-user-list', '/acesso/perfis/components/UserList', Record<never, never>, Record<never, never>>,
    'acesso-permissoes': RouteRecordInfo<'acesso-permissoes', '/acesso/permissoes', Record<never, never>, Record<never, never>>,
    'acesso-permissoes-components-add-edit-permission-dialog': RouteRecordInfo<'acesso-permissoes-components-add-edit-permission-dialog', '/acesso/permissoes/components/AddEditPermissionDialog', Record<never, never>, Record<never, never>>,
    'auth-esqueceu-senha': RouteRecordInfo<'auth-esqueceu-senha', '/auth/esqueceu-senha', Record<never, never>, Record<never, never>>,
    'auth-login': RouteRecordInfo<'auth-login', '/auth/login', Record<never, never>, Record<never, never>>,
    'auth-redefinir-senha': RouteRecordInfo<'auth-redefinir-senha', '/auth/redefinir-senha', Record<never, never>, Record<never, never>>,
    'auth-verificar-email': RouteRecordInfo<'auth-verificar-email', '/auth/verificar-email', Record<never, never>, Record<never, never>>,
    'fabricante': RouteRecordInfo<'fabricante', '/fabricante', Record<never, never>, Record<never, never>>,
    'fabricante-cadastrar': RouteRecordInfo<'fabricante-cadastrar', '/fabricante/cadastrar', Record<never, never>, Record<never, never>>,
    'fabricante-components-fabricante-form': RouteRecordInfo<'fabricante-components-fabricante-form', '/fabricante/components/FabricanteForm', Record<never, never>, Record<never, never>>,
    'fabricante-editar-id': RouteRecordInfo<'fabricante-editar-id', '/fabricante/editar/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'loja': RouteRecordInfo<'loja', '/loja', Record<never, never>, Record<never, never>>,
    'loja-cadastrar': RouteRecordInfo<'loja-cadastrar', '/loja/cadastrar', Record<never, never>, Record<never, never>>,
    'loja-components-loja-form': RouteRecordInfo<'loja-components-loja-form', '/loja/components/LojaForm', Record<never, never>, Record<never, never>>,
    'loja-editar-id': RouteRecordInfo<'loja-editar-id', '/loja/editar/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'produto': RouteRecordInfo<'produto', '/produto', Record<never, never>, Record<never, never>>,
    'produto-cadastrar': RouteRecordInfo<'produto-cadastrar', '/produto/cadastrar', Record<never, never>, Record<never, never>>,
    'produto-components-produto-form': RouteRecordInfo<'produto-components-produto-form', '/produto/components/ProdutoForm', Record<never, never>, Record<never, never>>,
    'produto-editar-id': RouteRecordInfo<'produto-editar-id', '/produto/editar/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'profile': RouteRecordInfo<'profile', '/profile', Record<never, never>, Record<never, never>>,
    'promocao': RouteRecordInfo<'promocao', '/promocao', Record<never, never>, Record<never, never>>,
    'promocao-cadastrar': RouteRecordInfo<'promocao-cadastrar', '/promocao/cadastrar', Record<never, never>, Record<never, never>>,
    'promocao-components-promocao-form': RouteRecordInfo<'promocao-components-promocao-form', '/promocao/components/PromocaoForm', Record<never, never>, Record<never, never>>,
    'promocao-editar-id': RouteRecordInfo<'promocao-editar-id', '/promocao/editar/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'users': RouteRecordInfo<'users', '/users', Record<never, never>, Record<never, never>>,
    'users-cadastrar': RouteRecordInfo<'users-cadastrar', '/users/cadastrar', Record<never, never>, Record<never, never>>,
    'users-components-form-users': RouteRecordInfo<'users-components-form-users', '/users/components/form-users', Record<never, never>, Record<never, never>>,
    'users-editar-id': RouteRecordInfo<'users-editar-id', '/users/editar/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
  }
}
