import type { ThemeDefinition } from 'vuetify'

export const staticPrimaryColor = '#507DBC'
export const staticPrimaryDarkenColor = '#3D6A9E'

export const themes: Record<string, ThemeDefinition> = {
  light: {
    dark: false,
    colors: {
      'primary': staticPrimaryColor,
      'on-primary': '#fff',
      'primary-darken-1': '#3D6A9E',
      'secondary': '#A1C6EA',
      'on-secondary': '#04080F',
      'secondary-darken-1': '#88AED4',
      'success': '#28C76F',
      'on-success': '#fff',
      'success-darken-1': '#24B364',
      'info': '#507DBC',
      'on-info': '#fff',
      'info-darken-1': '#3D6A9E',
      'warning': '#FF9F43',
      'on-warning': '#fff',
      'warning-darken-1': '#E68F3C',
      'error': '#FF4C51',
      'on-error': '#fff',
      'error-darken-1': '#E64449',
      'background': '#DAE3E5',
      'on-background': '#04080F',
      'surface': '#fff',
      'on-surface': '#04080F',
      'grey-50': '#F5F8FA',
      'grey-100': '#EDF2F7',
      'grey-200': '#DAE3E5',
      'grey-300': '#BBD1EA',
      'grey-400': '#A1C6EA',
      'grey-500': '#7FA8CC',
      'grey-600': '#507DBC',
      'grey-700': '#3D6A9E',
      'grey-800': '#1E3C5A',
      'grey-900': '#04080F',
      'grey-light': '#F5F8FA',
      'perfect-scrollbar-thumb': '#BBD1EA',
      'skin-bordered-background': '#fff',
      'skin-bordered-surface': '#fff',
      'expansion-panel-text-custom-bg': '#F5F8FA',
    },

    variables: {
      'code-color': '#d400ff',
      'overlay-scrim-background': '#04080F',
      'tooltip-background': '#04080F',
      'overlay-scrim-opacity': 0.5,
      'hover-opacity': 0.06,
      'focus-opacity': 0.1,
      'selected-opacity': 0.08,
      'activated-opacity': 0.16,
      'pressed-opacity': 0.14,
      'dragged-opacity': 0.1,
      'disabled-opacity': 0.4,
      'border-color': '#04080F',
      'border-opacity': 0.12,
      'table-header-color': '#BBD1EA',
      'high-emphasis-opacity': 0.9,
      'medium-emphasis-opacity': 0.7,
      'switch-opacity': 0.2,
      'switch-disabled-track-opacity': 0.3,
      'switch-disabled-thumb-opacity': 0.4,
      'switch-checked-disabled-opacity': 0.3,
      'track-bg': '#DAE3E5',

      // Shadows
      'shadow-key-umbra-color': '#04080F',
      'shadow-xs-opacity': 0.10,
      'shadow-sm-opacity': 0.12,
      'shadow-md-opacity': 0.14,
      'shadow-lg-opacity': 0.16,
      'shadow-xl-opacity': 0.18,
    },
  },
  dark: {
    dark: true,
    colors: {
      'primary': staticPrimaryColor,
      'on-primary': '#fff',
      'primary-darken-1': '#3D6A9E',
      'secondary': '#A1C6EA',
      'on-secondary': '#04080F',
      'secondary-darken-1': '#88AED4',
      'success': '#28C76F',
      'on-success': '#fff',
      'success-darken-1': '#24B364',
      'info': '#507DBC',
      'on-info': '#fff',
      'info-darken-1': '#3D6A9E',
      'warning': '#FF9F43',
      'on-warning': '#fff',
      'warning-darken-1': '#E68F3C',
      'error': '#FF4C51',
      'on-error': '#fff',
      'error-darken-1': '#E64449',
      'background': '#04080F',
      'on-background': '#DAE3E5',
      'surface': '#0C1829',
      'on-surface': '#DAE3E5',
      'grey-50': '#0C1829',
      'grey-100': '#142038',
      'grey-200': '#1A2A47',
      'grey-300': '#1E3C5A',
      'grey-400': '#2A5480',
      'grey-500': '#507DBC',
      'grey-600': '#7FA8CC',
      'grey-700': '#A1C6EA',
      'grey-800': '#BBD1EA',
      'grey-900': '#DAE3E5',
      'grey-light': '#142038',
      'perfect-scrollbar-thumb': '#2A5480',
      'skin-bordered-background': '#0C1829',
      'skin-bordered-surface': '#0C1829',
    },
    variables: {
      'code-color': '#d400ff',
      'overlay-scrim-background': '#04080F',
      'tooltip-background': '#A1C6EA',
      'overlay-scrim-opacity': 0.7,
      'hover-opacity': 0.08,
      'focus-opacity': 0.12,
      'selected-opacity': 0.1,
      'activated-opacity': 0.18,
      'pressed-opacity': 0.16,
      'dragged-opacity': 0.1,
      'disabled-opacity': 0.4,
      'border-color': '#BBD1EA',
      'border-opacity': 0.16,
      'table-header-color': '#1A2A47',
      'high-emphasis-opacity': 0.9,
      'medium-emphasis-opacity': 0.7,
      'switch-opacity': 0.4,
      'switch-disabled-track-opacity': 0.4,
      'switch-disabled-thumb-opacity': 0.8,
      'switch-checked-disabled-opacity': 0.3,
      'track-bg': '#1A2A47',

      // Shadows
      'shadow-key-umbra-color': '#04080F',
      'shadow-xs-opacity': 0.20,
      'shadow-sm-opacity': 0.24,
      'shadow-md-opacity': 0.28,
      'shadow-lg-opacity': 0.32,
      'shadow-xl-opacity': 0.36,
    },
  },
}

export default themes
